entries = [
  "Math-What is the square root of 16?-Easy-4",
  "Science-What is the name of the element with the atomic number 1?-Easy-Hydrogen",
  "English-What is the name of the main character in the novel \"Pride and Prejudice\"?-Easy-Elizabeth Bennet",
  "History-What year did the Battle of Gettysburg take place?-Easy-1863",
  "Computer Science-What is the name of the programming language that is used to create websites?-Easy-HTML",
  "Math-What is the formula for the area of a circle?-Medium-πr^2",
  "Science-What is the name of the force that keeps the Earth in orbit around the Sun?-Medium-Gravity",
  "English-What is the name of the play by William Shakespeare that is set in the forest of Arden?-Medium-As You Like It",
  "History-What is the name of the treaty that ended the American Civil War?-Medium-Treaty of Appomattox Court House",
  "Computer Science-What is the name of the operating system that is used on most Apple computers?-Medium-macOS",
  "Math-What is the formula for the volume of a sphere?-Hard-4/3πr^3",
  "Science-What is the name of the element with the atomic number 92?-Hard-Uranium",
  "English-What is the name of the novel by Leo Tolstoy that is set during the Napoleonic Wars?-Hard-War and Peace",
  "History-What is the name of the war that was fought between the United States and Mexico from 1846 to 1848?-Hard-Mexican-American War",
  "Computer Science-What is the name of the programming language that is used to create video games?-Hard-C++",
  "Math-What is the value of pi?-Easy-3.14159",
  "Science-What is the name of the largest ocean in the world?-Easy-Pacific Ocean",
  "English-What is the name of the play by William Shakespeare that is set in Denmark?-Easy-Hamlet",
  "History-What is the name of the first president of the United States?-Easy-George Washington",
  "Computer Science-What is the name of the programming language that is used to create mobile apps?-Easy-Java",
  "Math-What is the formula for the perimeter of a square?-Medium-4s",
  "Science-What is the name of the force that causes objects to fall to the ground?-Medium-Gravity",
  "English-What is the name of the novel by Jane Austen that is set in the English countryside?-Medium-Pride and Prejudice",
  "History-What is the name of the war that was fought between the United States and Spain from 1898 to 1899?-Medium-Spanish-American War",
  "Computer Science-What is the name of the operating system that is used on most Android devices?-Medium-Android",
  "Math-What is the formula for the area of a triangle?-Hard-(1/2)bh",
  "Science-What is the name of the element with the atomic number 6?-Hard-Carbon",
  "English-What is the name of the novel by Charles Dickens that is set in London?-Hard-Oliver Twist",
  "History-What is the name of the war that was fought between the United States and the Soviet Union from 1947 to 1991?-Hard-Cold War",
  "Computer Science-What is the name of the programming language that is used to create websites and web applications?-Hard-JavaScript",
  "Math-What is the formula for the area of a trapezoid?-Hard-1/2(b1+b2)h",
  "Science-What is the name of the element with the atomic number 26?-Hard-Iron",
  "English-What is the name of the novel by Jane Austen that is set in the English countryside?-Hard-Emma",
  "History-What is the name of the war that was fought between the United States and the Soviet Union in Afghanistan from 1979 to 1989?-Hard-Soviet-Afghan War",
  "Computer Science-What is the name of the programming language that is used to create"
]